### ISSUE TITLE
Move to ITRB

### ISSUE THREAD

**Issue by cbizon** [broadinstitute/genetics-kp-dev#47]
![image](https://user-images.githubusercontent.com/10744350/183755295-be38b386-0d2e-4246-9bf7-1f0c3f349507.png)

* Move production instance to ITRB asap ( I suspect that the development and production maturity levels are swapped in your smartapi registration)
* rename test to testing in x-maturity on smartapi registration

**Comment by tursynay** [comment]
@flannick, would you be the test person to assign this issue to?

**Comment by marcdubybroad** [comment]
Done; tests pass on https://arax.ncats.io/?smartapi=1
